#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname)

if [[ -f "$DOKKU_ROOT/$APP/SLACK_URL" || -f "$DOKKU_ROOT/SLACK_URL" ]]; then
  echo "-----> Notifying Slack ..."
  URL=$(dokku url $APP)
  LAST_COMMIT=$(dokku config:get $APP GIT_REV)
  GITHUB_REPO=$(dokku config:get $APP GITHUB_REPO_URL)
  SLACK_URL=$(cat "$DOKKU_ROOT/$APP/SLACK_URL" 2> /dev/null || cat "$DOKKU_ROOT/SLACK_URL" 2> /dev/null)
  SLACK_JSON="{
	\"blocks\": [
		{
			\"type\": \"header\",
			\"text\": {
				\"type\": \"plain_text\",
				\"text\": \"$HOSTNAME\",
				\"emoji\": true
			}
		},
		{
			\"type\": \"divider\"
		},
		{
			\"type\": \"section\",
			\"text\": {
				\"type\": \"mrkdwn\",
				\"text\": \":rocket: *$APP* was just deployed\"
			}
		},
		{
			\"type\": \"section\",
			\"text\": {
				\"type\": \"mrkdwn\",
				\"text\": \"Last commit: <$GITHUB_REPO/commits/$LAST_COMMIT|Click here> \\n Application available at: <$URL|$URL>\"
			}
		},
		{
			\"type\": \"divider\"
		}
	]
}"
  SLACK_RESULT=$(curl -s -d "payload=$SLACK_JSON" "${SLACK_URL}" -w "%{http_code}")
  echo "       ${SLACK_RESULT}"
fi
